# -*- coding: utf-8 -*-
"""MakeCSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pnmoEiB6YUhqH-xuEV8g0TDr4eMtvBqs
"""

import csv
import fileinput
import os
import re
import xml.etree.ElementTree as ET


def MakeCSV(filename):
    # bring file into elementtree format
    tree = ET.parse(filename)
    root = tree.getroot()
    listOfRows = []
    # iterate through div sections and create list of rows for csv
    for i in range(len(list(root[1][0]))):
        row = []
        name = str(root[1][0][i].attrib)
        name = filename + re.sub(r"[{},: .'n]", "", name)
        row.append(name)
        textsnippet = root[1][0][i].text
        row.append(textsnippet)
        listOfRows.append(row)
    with open("NEWCSV.csv", "w", encoding="UTF8") as f:
        # create writer object and write in header and row list
        writer = csv.writer(f)
        header = ["Section ID", "Text Section"]
        writer.writerow(header)
        for row in listOfRows:
            writer.writerow(row)


def AppendCSV(filename):
    # bring file into elementtree format
    tree = ET.parse(filename)
    root = tree.getroot()
    listOfRows = []
    # iterate through div sections and create list of rows for csv
    for i in range(len(list(root[1][0]))):
        row = []
        name = str(root[1][0][i].attrib)
        name = filename + re.sub(r"[{},: .'n]", "", name)
        row.append(name)
        textsnippet = root[1][0][i].text
        row.append(textsnippet)
        listOfRows.append(row)
    with open("NEWCSV.csv", "a", encoding="UTF8") as f:
        # create writer object and write in header and row list
        writer = csv.writer(f)
        for row in listOfRows:
            writer.writerow(row)


filenames = []
for filename in os.listdir("Data"):
    f = os.path.join("Data", filename)
    if os.path.isfile(f):
        filenames.append(f)

print(filenames)
MakeCSV(filenames[0])
for i in range(1, len(filenames)):
    AppendCSV(filenames[i])

import pickle

import pandas as pd

df = pd.read_csv("NEWCSV.csv")
df.to_pickle("pickledcsv.pkl")
