[project]
name = "Ai-in-Classics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "beautifulsoup4>=4.14.3",
    "bidict>=0.23.1",
    "cltk>=1.5.0",
    "datasets>=2.14.4",
    "deep-translator>=1.11.4",
    "dill>=0.3.7",
    "evaluate>=0.4.6",
    "fastapi>=0.136.0",
    "fastparquet>=2026.3.0",
    "gdown>=6.0.0",
    "graphviz>=0.21",
    "ipycache>=0.1.4",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "jupyterlite[all]>=0.7.4",
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "numpy>=1.26.4",
    "ollama>=0.6.1",
    "pandas>=3.0.2",
    "psycopg>=3.3.3",
    "psycopg2-binary>=2.9.11",
    "pyarrow>=23.0.1",
    "pydantic>=2.13.2",
    "pydot>=4.0.1",
    "pytest>=9.0.3",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.26",
    "scikit-learn>=1.8.0",
    "spacy>=3.7.5",
    "sqlalchemy>=2.0.49",
    "stanza>=1.11.1",
    "streamlit>=1.56.0",
    "tensor2tensor>=1.15.5",
    "termcolor>=3.3.0",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "transformers>=4.57.6",
    "uvicorn[standard]>=0.44.0",
    "vadersentiment>=3.3.2",
]
