version: '3.8'
services:
  db:
    image: postgres:15
    container_name: greek-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: greek_lemmatizer
    ports:
      - "5432:5432"